### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by arihantverma** [nodef/ifct2017#4]
It'd be really helpful, if it'd be a scope maintainers might want to work on still, to provide types (and descriptions) of all properties of each nutrient. Would help much in autocompletion, and in being able to see what `fatce`, `fibtg`, etc… properties mean ( from a developer perspective—from their description comment in editor autocomplete suggestions )

**Comment by wolfram77** [comment]
Occasionally these JS projects seems to be getting called back from the dead. I checked, and there is already in typescript definition file https://github.com/ifct2017/compositions/blob/master/index.d.ts

Do the type definitions not work now?

**Comment by arihantverma** [comment]
My editor's language server glitched and I utterly terribly missed the declaration file in the code, my apologies. As you were 🌻
